### ISSUE TITLE
Is it possible to run a backend for laion400m?

### ISSUE THREAD

**Issue by yaoliliu** [chenyangzhu1/LAION-Retrieval#1]
Hi there, I'm trying to recurrent Custom Diffusion and I'm wondering if using only a small subset of laion for retrieval would worsen the result. Do I have to download everything in https://the-eye.eu/public/AI/cah/laion400m-indexes/ to build a backend or this is not even enough? 
If I had to download the entire laion400m to build a usable clip_back, I guess using small subset is the only possible way...

**Comment by chenyangzhu1** [comment]
I am not sure if using only a small subset of LAIONs for retrieval will worsen the results. If you need to use LAION 400M as a retrieval dataset, it is necessary to download it completely to your local computer.

You can try to reproduce the custom diffusion method with a smaller subset (e.g., [improved_aesthetics_6.5plus](https://laion.ai/blog/laion-aesthetics/) in this repo) to verify whether its performance will be worse.

In addition, the [script](https://github.com/huggingface/diffusers/tree/main/examples/custom_diffusion) of custom diffusion in diffusers also supports using generated images as regularization.

Hope this helps :)
